### ISSUE TITLE
ARM compatiblilty

### ISSUE THREAD

**Issue by zakpatat** [lancachenet/docker-compose#11]
With the new Raspberry PI 4 released it would be really nice to have a docker compose file able to run on it. For small LAN parties this would make it really easy to deploy.

**Comment by MathewBurnett** [comment]
It is unlikely that we will go in this direction. Even for a small amount of people a successful cache would have access to fast disks. If i were personally to build a mini cache I would use something like a qotom (mini pc).

**Comment by FibreFoX** [comment]
@MathewBurnett 
A Raspberry Pi 4 can be extended with a SATA storage, or a NVMe-drive via USB, and as this is some cache-tool, why not adding ARM as a nice feature, where it only counts towards having stuff cached, and not just focusing on "high speed"? A "private LAN party" with a shared internet connection can benefit from an already existing RasPi which is running PiHole or any other convenience-tool might just host some instance of lancache too.

**Comment by MathewBurnett** [comment]
Someone has done a port to arm https://github.com/jrcichra/lancache-rpi however it isn't a core use case for us. For a 10 person sized LAN i would recommend a mini pc style solution or a second hand half depth 1u server.
