### ISSUE TITLE
Downloads extremely slow

### ISSUE THREAD

**Issue by TheImpossible21** [lancachenet/docker-compose#12]
Hi

Lancache downloads just stop downloading

So I have installed using socket compose and changed my dns on my pc to the ip I set in setup, when I start a steam download it starts of fine, I can see activity in the access log but after a few minutes it just drops off..

I have experienced this with steam and uplay, I did see  to add more ip’s I have gone ahead and done that it has a total of 10 ip’s now but no change.

When I change my dns back to my dns server which in turn is forwarded to 8.8.8.8 & 1.1.1.1 the downloads don’t drop off?

I’m at a loss now, any help would be appreciated.

**Comment by MathewBurnett** [comment]
i would recommend you head over to our discord for this and there are likely many follow up questions required to assist you. the details can be found on http://lancache.net/support/
