### ISSUE TITLE
Running without .env?

### ISSUE THREAD

**Issue by SelfhostedPro** [lancachenet/docker-compose#15]
Is it possible to specify environment variables instead of using a .env file? Looking to add a portainer template for it via: https://github.com/SelfhostedPro/selfhosted_templates/issues/97

**Comment by jdawgzim** [comment]
Maybe the docker variables could help generate the first .env file?  

I think https://hub.docker.com/r/itzg/minecraft-server/ does something like this to generate the config file.

**Comment by MathewBurnett** [comment]
the .env file simply loads all of the variables in to each container. While not all the containers need all of them you will be quite robust to any changes if you simply add an environment key to the compose for each with all the values in them. see https://docs.docker.com/compose/environment-variables/ for detail of how to do that in compose files
