### ISSUE TITLE
Cache size limit of around 4,5TB

### ISSUE THREAD

**Issue by Pete13B** [lancachenet/docker-compose#16]
Used the monolithic version for a while without to many issues.
Recently I moved to the docker-compose version for simplicity.
After a while I came across a problem that my total cache size on disk reduced itself to around 4,5 - 4,6 TB.
While it goes further than that (seen it go to 5,1TB), if the service is restarted, after a while the disk size is reduced again.
Because this does not seem to be intended in the configuration and I am not very good with Linux, I wanted to inform if there is a way to fix this?
First I used the default cache_slice_size of 1m and am using the 8m slice at the moment.
I tried changing the Cache_disk_size from 6000000m to 6000g with no improvement.
Except for the size shrinkage everything seems to be working fine and installing games at 300MB/s is really fun.

My .env config.
USE_GENERIC_CACHE=true
LANCACHE_IP=192.168.2.90 192.168.2.91 192.168.2.92 1692.168.2.93
DNS_BIND_IP=192.168.2.90
UPSTREAM_DNS=192.168.2.1
CACHE_ROOT=./lancache
CACHE_MEM_SIZE=1000m
CACHE_DISK_SIZE=6000g
CACHE_MAX_AGE=3650d
CACHE_SLICE_SIZE=8m

If any other info is needed, please let me know.

Thanks in advance for looking into it.

**Comment by MathewBurnett** [comment]
How are you confirming the size on disk of your cache?

**Comment by Pete13B** [comment]
By using the command df /dev/mapper/ubuntu--vg-root
I know this is including the operating system and software, but by caching terabytes it doesn't have a large impact I think.

**Comment by Pete13B** [comment]
When looking in the sudo docker exec -it lancache_monolithic_1 tail -f /data/logs/access.log everything seems normal and size keeps growing until I see the following line in de logs and the total used disk size shrinks back to about 4,5TB (from 5,2TB this time).
[127.0.0.1] 127.0.0.1 / - - - [05/Jul/2020:13:56:46 +0100] "GET /lancache-heartbeat HTTP/1.1" 204 0 "-" "Wget/1.19.4 (linux-gnu)" "-" "127.0.0.1" "-"
Thats the only line that seems different than the others at around the time period the size shrinks.
It kinda seems like and integer limit some (don't know much about coding).
https://en.wikipedia.org/wiki/4,294,967,295

**Comment by MathewBurnett** [comment]
6000g won't work as nginx wont recognise anything other than m. However i can assure you we use a cache with over 6tb of space successfully
