### ISSUE TITLE
Error running on raspberry with docker

### ISSUE THREAD

**Issue by rubensamuelJesus** [lancachenet/docker-compose#23]
Hi, I was trying to run lancachenet on raspberry using docker, but if i try to create a container with  lancachenet/monolithic:latest image, give me error.
The try it to run in a virtual machine and works good.
I'm thinking that the problem is because of the operating system

![image](https://user-images.githubusercontent.com/38758906/109436672-8ee35900-7a18-11eb-8a82-76fee269845a.png)

and some info about docker 

![image](https://user-images.githubusercontent.com/38758906/109436706-b20e0880-7a18-11eb-9a8e-a8a7b42fe97a.png)

is there anything you guys can do, to change the image to work on raspberry

**Comment by mari0theminer** [comment]
try: https://github.com/jrcichra/lancache-rpi it has arm suport
