### ISSUE TITLE
Can't define IPv6 addresses in .env

### ISSUE THREAD

**Issue by unquietwiki** [lancachenet/docker-compose#25]
Example: using **fe80::d** as a local subnet IPv6 DNS address...

`services.dns.ports is invalid: Invalid port ":53:53/tcp", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]`

https://docs.docker.com/compose/compose-file/compose-file-v3/ support does exist; otherwise, port-forwarding could be set up via haproxy or other UDP/TCP dual-stack port forwarding software.

Thanks for making this!

**Comment by MathewBurnett** [comment]
At present the solution is entirely ipv4, this is mostly historical but also because its far easy to organise LAN firewalls around. We have not yet settled on exactly how we wish to tackle ipv6 although it is on our mind.
