### ISSUE TITLE
Multiple Services

### ISSUE THREAD

**Issue by Joly0** [lancachenet/docker-compose#4]
Hey, i just tried to figure out, how to edit the compose file, so i can use different ip adresses for the different services but i am not quite sure, how this works.

Is there a way to do that? 

I never used Compose before but i work with Docker, so i am no "newb"

**Comment by VibroAxe** [comment]
Docker compose is moving over to our monolithic system (See #5) which means all the services will run through the same cache. Generic is no longer our recommended system unless you have a definitive need for single containers
