### ISSUE TITLE
Steam works, Epic games or Riot does not work at all. 

### ISSUE THREAD

**Issue by coco74x** [lancachenet/docker-compose#7]
Hi,
I have been doing some test of lancache with the suggested default configuration with docker-compose.yml file. I of course modify the .env conf with my settings and I launch the stack with docker compose.

It is exactly the configuration files from github with the .env modified.

I tested with Steam, Epic launcher, and League of Legends (riot). The steam games are cached by my lancache server, but Epic games or Riot games does not work at all. There is nothing working at all, it is impossible to download anything (the launchers are totaly locked).

On the .env file, I just modified the IP with my server IP, and the DNS by 1.1.1.1. Steam works, the other don't.

Can I do anything ? Is it an issue with lancache ?
Thanks for helping me :)

**Comment by VibroAxe** [comment]
The docker-compose is somewhat out of date and not currently our recommended solution. We are in the process of updating ( see #5 ) which will become the default install method for lancache.net once it is complete
